# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    user_provider:
      entity:
        class: AppBundle:User
        property: mail


  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    other:
      pattern: ^/login
      security: false

    main:
      guard:
        authenticators:
          - app.token_authenticator
      stateless: true

  access_control:
    - { path: ^/, roles: ROLE_ADMIN, methods: [POST, PUT] }
    - { path: ^/users, roles: ROLE_ADMIN, methods: [GET] }
