# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.user_service:
    class: AppBundle\Services\UserService
    arguments: ['@doctrine.orm.entity_manager']
  app.technique_service:
    class: AppBundle\Services\TechniqueService
    arguments: ['@doctrine.orm.entity_manager']
  app.token_authenticator:
    class: AppBundle\Security\TokenAuthenticator
    arguments: ['@app.user_service']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
